export const REQUEST_ALL_POSTS = 'REQUEST_ALL_POSTS';
export const ALL_POSTS_SUCCESS = 'ALL_POSTS_SUCCESS';
export const ALL_POSTS_FAILED = 'ALL_POSTS_FAILED';
export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
