export const REQUEST_POST_COMMENTS = 'REQUEST_POST_COMMENTS';
export const POST_COMMENTS_SUCCESS = 'POST_COMMENTS_SUCCESS';
export const POST_COMMENTS_FAILED = 'POST_COMMENTS_FAILED';
export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';
export const RESET_POST_COMMENTS = 'RESET_POST_COMMENTS';
